0xSpaceShard/starknet-hardhat-example

package-lock.json, package.json, test/sample-test.ts, test/signing-tests.ts
Refactored signing tests to a different test file
=> Refactored signing tests to a different test file

contracts/contract.cairo, test/sample-test.ts
Added input tests on contract and mocha test file
=> Added input tests on contract and mocha test file

scripts/compile-contract.ts
To test the overriden `hardhat run` task.
=> Add compile-contract script

contracts/empty_constructor.cairo, contracts/simple_storage.cairo, test/constructor.test.ts, test/sample-test.ts
- Systematize how constructor testing is done (in a separate file).
=> Add constructor testing

.gitignore, hardhat.config.ts, package-lock.json, package.json, test/oz-account-test.ts
* Bump dockerized version
* Modify low max fee test
* Update hardhat to 2.9.3
=> Adapt 0.8.1

.gitignore, hardhat.config.ts, package-lock.json, package.json, test/oz-account-test.ts
Reverts Shard-Labs/starknet-hardhat-example#46
=> Revert "Adapt 0.8.1"

test/sample-test.ts
* Introduced here https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/97
=> New test to check get block utility function

test/argent-account-test.ts, test/oz-account-test.ts
Corresponding plugin PR: https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/100
=> Deploy account options

test/integrated-devnet-args.test.ts
Test arguments passed on `hardhat.config.ts` file for integrated-devnet network.
=> Integrated-devnet optional arguments test

contracts/events.cairo, test/decode-events.test.ts, test/sample-test.ts, test/util.ts
Exemple of how "contract.decodeEvents" function works
=> add decode events test

test/devnet-create-block.test.ts
Test for https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/203
=> Test createBlock

tsconfig.json
Adds `"resolveJsonModule": true` to tsconfig to resolve `.json` module import issue.
=> Add resolveJsonModule to import module with .json

test/contract-factory.test.ts, test/contract.test.ts
=> Y u no declare

test/get-balance.test.ts
Related to: https://github.com/Shard-Labs/starknet-hardhat-plugin/pull/306
=> Add tests for getBalance function

.env.example, scripts/deploy-account.ts
=> 90 env example

hardhat.config.ts, scripts/deploy-account.ts
- Improve deploy-account script:
- Check if balance not 0
- Log tx hash
- Re-enable defaulting to newly generated salt and private key
- Expand default hardhat config file:
- Add integration network configuration
=> Improve account deploy

hardhat.config.ts, scripts/compile-contract.ts
Paired with https://github.com/0xSpaceShard/starknet-hardhat-plugin/pull/345
=> Use custom cairo 1 compilation binaries

cairo1-contracts/events.cairo, hardhat.config.ts, package-lock.json, package.json, test/cairo1/declare-v2.test.ts, test/cairo1/decode-events.test.ts
Add cairo1 events test (https://github.com/0xSpaceShard/starknet-hardhat-plugin/issues/378). Linked with https://github.com/0xSpaceShard/starknet-hardhat-plugin/pull/380
- add a `test/cairo1` directory
- moved `declare-v2-test` to test/cairo1 directory
- add starknet.js ^4.22.0 to handle uint256
=> Cairo1 events

contracts/replaceable.cairo, scripts/replace.ts
- Fixes the replacable.cairo contract by adding the missing return.
- Fixes the replace.ts script by doing what is expected - replaces the implementation of the class.
=> Fix replacement

cairo1-contracts/events.cairo
Updating events.cairo example to use Cairo 2 syntax
=> Updated events to cairo2

.gitignore, hardhat.config.ts
Updates `hardhat.config.ts` file
=> Compiler downloader

.github/workflows/main.yml, cairo1_sample_project/src/fib_contract.cairo, cairo1_sample_project/src/multiple_contracts.cairo, hardhat.config.ts, package.json
- Reorganizes comments in hardhat.config.ts:
- Cairo 0 compilation moved downward
- Improved naming in CI/CD workflow
- Cairo contracts from Scarb sample project updated to Cairo 2.2.0
=> Prepare release of plugin 0.8.0-alpha.5
